[E 2025-08-20 00:04:31,842 D:\Python\Python310\lib\site-packages\shioaji\utils.py:49:raise_resp_error] {'status': {'status_code': 451}, 'response': {'token': '', 'accounts': [], 'detail': 'Too Many Connections.', 'ip_address': '125.227.58.59', 'person_id': 'F229203949', 'client_name': '', 'contract_download': False, 'web_token': '', 'solace_props': None}}
[E 2025-08-20 00:05:09,078 D:\Python\Python310\lib\site-packages\shioaji\utils.py:49:raise_resp_error] {'status': {'status_code': 451}, 'response': {'token': '', 'accounts': [], 'detail': 'Too Many Connections.', 'ip_address': '125.227.58.59', 'person_id': 'F229203949', 'client_name': '', 'contract_download': False, 'web_token': '', 'solace_props': None}}
[E 2025-08-20 01:07:57,056 D:\Python\Python310\lib\site-packages\shioaji\utils.py:49:raise_resp_error] {'status': {'status_code': 451}, 'response': {'token': '', 'accounts': [], 'detail': 'Too Many Connections.', 'ip_address': '125.227.58.59', 'person_id': 'F229203949', 'client_name': '', 'contract_download': False, 'web_token': '', 'solace_props': None}}
[E 2025-08-20 02:49:20,822 D:\Python\Python310\lib\site-packages\shioaji\utils.py:49:raise_resp_error] {'status': {'status_code': 451}, 'response': {'token': '', 'accounts': [], 'detail': 'Too Many Connections.', 'ip_address': '125.227.58.59', 'person_id': 'F229203949', 'client_name': '', 'contract_download': False, 'web_token': '', 'solace_props': None}}
